src/Entity/Etapes.php
<?php

namespace App\Entity;

use App\Repository\EtapesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtapesRepository::class)]
class Etapes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Descriptif = null;

    #[ORM\Column(length: 1000)]
    private ?string $Consignes = null;

    #[ORM\Column]
    private ?int $Position = null;

    #[ORM\ManyToOne(inversedBy: 'etapes')]
    private ?Parcours $parcours = null;

    /**
     * @var Collection<int, RendusActivites>
     */
    #[ORM\ManyToMany(targetEntity: RendusActivites::class, mappedBy: 'etapes')]
    private Collection $rendusActivites;

    #[ORM\ManyToOne(inversedBy: 'etapes')]
    private ?Ressources $ressources = null;

    public function __construct()
    {
        $this->rendusActivites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescriptif(): ?string
    {
        return $this->Descriptif;
    }

    public function setDescriptif(string $Descriptif): static
    {
        $this->Descriptif = $Descriptif;

        return $this;
    }

    public function getConsignes(): ?string
    {
        return $this->Consignes;
    }

    public function setConsignes(string $Consignes): static
    {
        $this->Consignes = $Consignes;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->Position;
    }

    public function setPosition(int $Position): static
    {
        $this->Position = $Position;

        return $this;
    }

    public function getParcours(): ?Parcours
    {
        return $this->parcours;
    }

    public function setParcours(?Parcours $parcours): static
    {
        $this->parcours = $parcours;

        return $this;
    }

    /**
     * @return Collection<int, RendusActivites>
     */
    public function getRendusActivites(): Collection
    {
        return $this->rendusActivites;
    }

    public function addRendusActivite(RendusActivites $rendusActivite): static
    {
        if (!$this->rendusActivites->contains($rendusActivite)) {
            $this->rendusActivites->add($rendusActivite);
            $rendusActivite->addEtape($this);
        }

        return $this;
    }

    public function removeRendusActivite(RendusActivites $rendusActivite): static
    {
        if ($this->rendusActivites->removeElement($rendusActivite)) {
            $rendusActivite->removeEtape($this);
        }

        return $this;
    }

    public function getRessources(): ?Ressources
    {
        return $this->ressources;
    }

    public function setRessources(?Ressources $ressources): static
    {
        $this->ressources = $ressources;

        return $this;
    }
}

src/Entity/Parcours.php
<?php

namespace App\Entity;

use App\Repository\ParcoursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ParcoursRepository::class)]
class Parcours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Objet = null;

    #[ORM\Column(length: 1000)]
    private ?string $Description = null;

    #[ORM\ManyToOne(inversedBy: 'parcours')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, Etapes>
     */
    #[ORM\OneToMany(targetEntity: Etapes::class, mappedBy: 'parcours')]
    private Collection $etapes;

    public function __construct()
    {
        $this->etapes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getObjet(): ?string
    {
        return $this->Objet;
    }

    public function setObjet(string $Objet): static
    {
        $this->Objet = $Objet;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Etapes>
     */
    public function getEtapes(): Collection
    {
        return $this->etapes;
    }

    public function addEtape(Etapes $etape): static
    {
        if (!$this->etapes->contains($etape)) {
            $this->etapes->add($etape);
            $etape->setParcours($this);
        }

        return $this;
    }

    public function removeEtape(Etapes $etape): static
    {
        if ($this->etapes->removeElement($etape)) {
            // set the owning side to null (unless already changed)
            if ($etape->getParcours() === $this) {
                $etape->setParcours(null);
            }
        }

        return $this;
    }
}

src/Form/ParcoursForm.php
<?php

namespace App\Form;

use App\Entity\Parcours;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ParcoursForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Objet')
            ->add('Description')
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Parcours::class,
        ]);
    }
}

src/Controller/ParcoursController.php
<?php

namespace App\Controller;

use App\Entity\Parcours;
use App\Form\ParcoursForm;
use App\Repository\ParcoursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/parcours')]
final class ParcoursController extends AbstractController
{
    #[Route(name: 'app_parcours_index', methods: ['GET'])]
    public function index(ParcoursRepository $parcoursRepository): Response
    {
        return $this->render('parcours/index.html.twig', [
            'parcours' => $parcoursRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_parcours_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $parcours = new Parcours();
        $form = $this->createForm(ParcoursForm::class, $parcours);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($parcours);
            $entityManager->flush();

            return $this->redirectToRoute('app_parcours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('parcours/new.html.twig', [
            'parcours' => $parcours,
            'form' => $form,
        ]);
    }

    #[Route('/parcours/{id}', name: 'app_parcours_show')]
    // #[IsGranted('ROLE_USER')]
    public function show(Parcours $parcours): Response
    {
        // Vérifie que l'utilisateur a le droit d'accéder à ce parcours
        // if ($parcours->getUser() !== $this->getUser()) {
        //     throw $this->createAccessDeniedException();
        // }

        return $this->render('parcours/show.html.twig', [
            'parcours' => $parcours,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_parcours_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Parcours $parcours, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ParcoursForm::class, $parcours);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_parcours_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('parcours/edit.html.twig', [
            'parcours' => $parcours,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_parcours_delete', methods: ['POST'])]
    public function delete(Request $request, Parcours $parcours, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $parcours->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($parcours);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_parcours_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/parcours/_delete_form.html.twig
<form method="post" action="{{ path('app_parcours_delete', {'id': parcour.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ parcour.id) }}">
    <button class="btn">Delete</button>
</form>

templates/parcours/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/parcours/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Parcours{% endblock %}

{% block body %}
    <h1>Edit Parcours</h1>

    {{ include('parcours/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_parcours_index') }}">back to list</a>

    {{ include('parcours/_delete_form.html.twig') }}
{% endblock %}

templates/parcours/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parcours index{% endblock %}

{% block body %}
    <h1>Parcours index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Objet</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for parcour in parcours %}
            <tr>
                <td>{{ parcour.id }}</td>
                <td>{{ parcour.Objet }}</td>
                <td>{{ parcour.Description }}</td>
                <td>
                    <a href="{{ path('app_parcours_show', {'id': parcour.id}) }}">show</a>
                    <a href="{{ path('app_parcours_edit', {'id': parcour.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_parcours_new') }}">Create new</a>
{% endblock %}

templates/parcours/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Parcours{% endblock %}

{% block body %}
    <h1>Create new Parcours</h1>

    {{ include('parcours/_form.html.twig') }}

    <a href="{{ path('app_parcours_index') }}">back to list</a>
{% endblock %}

templates/parcours/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Parcours : {{ parcours.objet }}</h1>

    {% if parcours.etapes is empty %}
        <div class="alert alert-info">Aucune étape pour ce parcours.</div>
    {% else %}
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Intitulé</th>
                </tr>
            </thead>
            <tbody>
                {% for etape in parcours.etapes %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ etape.descriptif }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}

    <a href="{{ path('app_parcours_index') }}" class="btn btn-secondary">
        Retour à la liste
    </a>
{% endblock %}